# json_convert - Paquete de módulos para extracción de datos Adobe Analytics
from json_convert.aa_parser import (
    AA_DOMAINS,
    DATA_LAYER_NAMES,
    build_aa_from_s,
    extract_digital_data,
    extract_s_object,
    extract_title,
    parse_aa_beacon,
    try_dismiss_cookie_consent,
)
from json_convert.cache import UrlCache
from json_convert.excel import (
    CONTROL_HEADERS,
    DATA_FILLS,
    HEADER_FILLS,
    INPUT_FILE,
    SAVE_EVERY_N,
    SHEET_HEADERS,
    _auto_row_height,
    _has_json_data,
    _is_json_error,
    _pretty_json,
    _set_col_widths,
    _write_cell,
    apply_data_fills,
    print_progress,
    save_workbook,
    setup_multisheet,
    split_aa_workbooks,
    update_control,
    update_vars_sheet,
    validate_sheet,
)
from json_convert.metrics import (
    ERROR_CODES,
    _error_code_from_detail,
    classify_errors,
    compute_score,
    compute_url_score,
)
from json_convert.pipeline import (
    route_beacons,
    run_pipeline,
    write_result,
)
from json_convert.validation import (
    ALLOWED_HOSTNAME_SUFFIXES,
    VALID_URL_SCHEMES,
    sanitize_url_for_log,
    validate_url,
)

__all__ = [
    "AA_DOMAINS",
    "ALLOWED_HOSTNAME_SUFFIXES",
    "CONTROL_HEADERS",
    "DATA_FILLS",
    "DATA_LAYER_NAMES",
    "ERROR_CODES",
    "HEADER_FILLS",
    "INPUT_FILE",
    "SAVE_EVERY_N",
    "SHEET_HEADERS",
    "VALID_URL_SCHEMES",
    "UrlCache",
    "_auto_row_height",
    "_error_code_from_detail",
    "_has_json_data",
    "_is_json_error",
    "_pretty_json",
    "_set_col_widths",
    "_write_cell",
    "apply_data_fills",
    "build_aa_from_s",
    "classify_errors",
    "compute_score",
    "compute_url_score",
    "extract_digital_data",
    "extract_s_object",
    "extract_title",
    "parse_aa_beacon",
    "print_progress",
    "route_beacons",
    "run_pipeline",
    "sanitize_url_for_log",
    "save_workbook",
    "setup_multisheet",
    "split_aa_workbooks",
    "try_dismiss_cookie_consent",
    "update_control",
    "update_vars_sheet",
    "validate_sheet",
    "validate_url",
    "write_result",
]
